### ISSUE TITLE
Nuscenes Test Set Reproduction

### ISSUE THREAD

**Issue by zw615** [fundamentalvision/BEVFormer#109]
Hi, Thank you for the great work!

I wonder how I can the reproduce the Nuscenes Test Set leaderboard results (48.1mAP, 56.9NDS)? 

Thanks a lot!

**Comment by htian01** [comment]
Simplely using both train and val dataset as train and submit the result to the evaluatopn server.

**Comment by NuanBaobao** [comment]
Thank you! I have submitted the results and gotten the grade.

**Comment by russellyq** [comment]
Hi, @NuanBaobao @htian01 

How should I generate test results and submit to server ? Any guidelines ?

**Comment by khy-111** [comment]
> 谢谢！我已经提交了成绩，并拿到了分数。

可以上传一下你的配置文件吗
