### ISSUE TITLE
Any news on when will this repo be updated?

### ISSUE THREAD

**Issue by timothylimyl** [fundamentalvision/BEVFormer#112]
hi @zhiqi-li , any plans to update this repo to include more features (seg head, refactoring, ++ version, etc)?

**Comment by hli2020** [comment]
All new features, including BEVFormer++ on Waymo results will be updated here: https://github.com/OpenPerceptionX/BEVPerception-Survey-Recipe/tree/dev. will merge into Master soon.

**Comment by timothylimyl** [comment]
hi @hli2020 , is this an effort to be the "mmcv BEV"?  It will be exciting to see the BEV repo allowing custom datasets like mmseg and mmdet.

it seems like a long way to having the model components integrated in `OpenPerceptionX/BEV` as it only has data augmentation in the toolbox now. When do you think will BEVFormer++ be added?
