### ISSUE TITLE
Errors on python setup.py install

### ISSUE THREAD

**Issue by sinsin1998** [fundamentalvision/BEVFormer#113]
I install step by step but it gives me that
![image](https://user-images.githubusercontent.com/82814185/195279212-419c8be7-262b-40fc-87ab-fe2334045d1e.png)

**Comment by s7desai** [comment]
@zhangdi-trying What did you do for this error? Did you upgrade the numpy version or did you ignore it?

**Comment by zhangdi-trying** [comment]
> 

I have down nothing. After this error occurs, I try to update the numpy, but it give me this
![image](https://user-images.githubusercontent.com/82814185/201026393-1f27169a-6224-4e7f-b6c6-feac91ac8f30.png)

**Comment by leslieburke** [comment]
@zhangdi-trying did u solve it?i miss the same problem

**Comment by zhangdi-trying** [comment]
> 

no

**Comment by zhangdi-trying** [comment]
> @zhangdi-trying did u solve it?i miss the same problem

I got it!  You should change the version of panda, such as pip install pandas=1.4.4. Then you can run python install setup
