### ISSUE TITLE
Error: Invalid box type: None问题

### ISSUE THREAD

**Issue by Isaac-xie** [fundamentalvision/BEVFormer#115]
作者你好，在我安装完毕环境之后运行以下命令进行测试时，在评估阶段会出现以下问题：
raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None
请问是什么原因导致的呢

**Comment by apollo910** [comment]
Same issue.

**Comment by Isaac-xie** [comment]
look this,
https://github.com/fundamentalvision/BEVFormer/issues/45

**Comment by apollo910** [comment]
Ok, thanks a lot!
