### ISSUE TITLE
GFLOPs for attention and deformable attention

### ISSUE THREAD

**Issue by buaazeus** [fundamentalvision/BEVFormer#116]
Hello, I add forward_dummy and dummy_meta code, and use get_flops.py to calculate the flops.
But seems many calculate function (torchstat, ptflops, etc.) doesn't support attention layer or deformable attention layer very well.
Can you please share the code to calculate flops of attention layer and deformable attention layer?
Thank you.

**Comment by zhiqi-li** [comment]
Hi, the mmdet supports the calculation of the deformable attention layer, just using `get_flops` in mmdet is ok. But mmdet doesn't support the calculation of the attention layer.

**Comment by hrkssk** [comment]
Hi. Can you share how to add forward_dummy and dummy_meta code?
Thanks.

**Comment by buaazeus** [comment]
def forward_dummy(self, img):
        from mmdet3d.core.bbox.structures.box_3d_mode import LiDARInstance3DBoxes
        dummy_metas = {
                    'scene_token': 'c3ab8ee2c1a54068a72d7eb4cf22e43d', 
                    'can_bus': np.random.random((18)),
                    'lidar2img': [np.random.random((4,4))]*6,
                    'img_shape': [(928, 1600, 3)]*6,
                    "box_type_3d":LiDARInstance3DBoxes, 
                    }
        return self.forward_dummy_test(img=img, img_metas=[[dummy_metas]])

**Comment by admyxs** [comment]
> ```
> def forward_dummy(self, img):
>     from mmdet3d.core.bbox.structures.box_3d_mode import LiDARInstance3DBoxes
>     dummy_metas = {
>                 'scene_token': 'c3ab8ee2c1a54068a72d7eb4cf22e43d', 
>                 'can_bus': np.random.random((18)),
>                 'lidar2img': [np.random.random((4,4))]*6,
>                 'img_shape': [(928, 1600, 3)]*6,
>                 "box_type_3d":LiDARInstance3DBoxes, 
>                 }
>     return self.forward_test(img=img, img_metas=[[dummy_metas]])
> ```


Hello, thank for your work, but i want to know what the input_shape is,
or which command do you run?
can you explain for me?
thx
