### ISSUE TITLE
What is num_bev_level?

### ISSUE THREAD

**Issue by Qi-Zhangyang** [fundamentalvision/BEVFormer#121]
https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L200

bs, len_bev, num_bev_level, _ = ref_2d.shape

What is the num_bev_level? It shoule be bs?

**Comment by zhiqi-li** [comment]
It is the number of different bev scales. In bevformer, we use single-scale bev representation, but multi-scale bev features can be a potential design.

**Comment by Qi-Zhangyang** [comment]
Thanks very much.
