### ISSUE TITLE
a small error of spatial_cross_attention

### ISSUE THREAD

**Issue by Qi-Zhangyang** [fundamentalvision/BEVFormer#123]
https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/spatial_cross_attention.py#L139

        indexes = []
        for i, mask_per_img in enumerate(bev_mask): # bev_mask: [6(num_cam), 2(bs), 2500(bev_h*bev_w), 4(height)]
            index_query_per_img = mask_per_img[0].sum(-1).nonzero().squeeze(-1) # mask_per_img: [2(bs), 2500(bev_h*bev_w), 4(height)]
            indexes.append(index_query_per_img)
        max_len = max([len(each) for each in indexes])
        # index_query_per_img: Choose the first batch and get the bev query indexes which appear in the specific view.

Here the SCA index is determined by the first batch? Is it reasonable?
Thank you very much.

**Comment by zhiqi-li** [comment]
Yes, this may cause bugs while samples in the batch have different camera parameters.
For the current setting, samples own the same camera parameters, so that it is ok.

**Comment by Qi-Zhangyang** [comment]
Thanks very much.

**Comment by lawrence-cj** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/55283454/213624709-a337fb0e-a79f-4a85-90a4-e528879ff95c.png">
Sorry for the interuption, it seems that the parameters in different batch are not the same exactly.

**Comment by sodalone** [comment]
FYI 
```
indexes = []
# bev_mask: num_cam, bs, bev_h*bev_w, depth
for j in range(bs):
    indexes_per_batch = []
    for i, mask_per_img in enumerate(bev_mask):
        index_query_per_img = mask_per_img[j].sum(-1).nonzero().squeeze(-1)
        indexes_per_batch.append(index_query_per_img)
    indexes.append(indexes_per_batch)
max_len = max([len(each) for each in chain.from_iterable(indexes)])
# each camera only interacts with its corresponding BEV queries. This step can  greatly save GPU memory.
queries_rebatch = query.new_zeros([bs, self.num_cams, max_len, self.embed_dims])
reference_points_rebatch = reference_points_cam.new_zeros(
    [bs, self.num_cams, max_len, D, 2]
)
for j in range(bs):
    for i, reference_points_per_img in enumerate(reference_points_cam):
        index_query_per_img = indexes[j][i]
        queries_rebatch[j, i, : len(index_query_per_img)] = query[
            j, index_query_per_img
        ]
        reference_points_rebatch[
            j, i, : len(index_query_per_img)
        ] = reference_points_per_img[j, index_query_per_img]
```
