### ISSUE TITLE
What is the meaning and the influence of shift and shift_ref_2d?

### ISSUE THREAD

**Issue by Qi-Zhangyang** [fundamentalvision/BEVFormer#124]
https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L123-L141

https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L193-L209

![02E1B97F296516EAD5D4ABEFF2C841D3](https://user-images.githubusercontent.com/95071409/199048310-b280f065-96e6-4026-beca-7288ef94d952.png)

The fig shows how ref_2d becomes the shift_ref_2d. But I want to know the impact of it?
Thanks very much!

**Comment by zhiqi-li** [comment]
The influence is pretty minimal due to the translation being pretty small.

**Comment by Qi-Zhangyang** [comment]
Thanks very much.

**Comment by pierrelzw** [comment]
if `ref_2d` in global frame, shift is translation of bev_feature in global frame
we obtain `shift_ref_2d` with `shift_ref_2d += shift[:, None, None, :]`,
why  `shift_ref_2d` is in lidar_frame?

**Comment by pierrelzw** [comment]
> what is the meaning of shift, shift_ref_2d? Is `ref_2d` in global frame and is `shift` the translation of bev_feature in global frame？ we obtain `shift_ref_2d` with `shift_ref_2d += shift[:, None, None, :]`, why `shift_ref_2d` is in lidar_frame?
> 
> In the code to build can_bus, we use `ego2global_translation`, not ego2ego_pre_frame, it make me confused.

`shift` is the translation of bev_feat between t and t-1.  In the code to build can_bus, we use `ego2global_translation` and pre_pose to get the translation between t and t-1
