### ISSUE TITLE
What is the usage of self.rotation_pre_bev?

### ISSUE THREAD

**Issue by Qi-Zhangyang** [fundamentalvision/BEVFormer#125]
https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L143-L156

I wanna know if rotation of pre_bev can improve the performence?

Thank u very much.

**Comment by zhiqi-li** [comment]
> And there is a small error. The rotation center is always [100, 100] whatever the bev_h and bev_w are.
> 
> https://github.com/fundamentalvision/BEVFormer/blob/074e3688cc4fa30dd4de3ac034227f125b61157e/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L50-L68

Yes, while using different bev size, we should adjust the rotate_center.

**Comment by Qi-Zhangyang** [comment]
Thanks very much.
