### ISSUE TITLE
Question about temporal BEV feature alignment

### ISSUE THREAD

**Issue by airocking** [fundamentalvision/BEVFormer#138]
# Question about temporal BEV feature alignment

hello, ziqi, thanks for the greate works!
I have a question about the temporal BEV alignment 

          delta_x = np.array([each['can_bus'][0]
                            for each in kwargs['img_metas']])
            delta_y = np.array([each['can_bus'][1]
                            for each in kwargs['img_metas']])
            ego_angle = np.array(
                [each['can_bus'][-2] / np.pi * 180 for each in kwargs['img_metas']])  # ego angle
            grid_length_y = grid_length[0]
            grid_length_x = grid_length[1]
            translation_length = np.sqrt(delta_x ** 2 + delta_y ** 2)
            translation_angle = np.arctan2(delta_y, delta_x) / np.pi * 180
            bev_angle = ego_angle - translation_angle
            shift_y = translation_length * \
                np.cos(bev_angle / 180 * np.pi) / grid_length_y / bev_h            <------------------ -> np.sin
            shift_x = translation_length * \
                np.sin(bev_angle / 180 * np.pi) / grid_length_x / bev_w            <------------------- -> np.cos
            shift_y = shift_y * self.use_shift
            shift_x = shift_x * self.use_shift
===============================================
I think the `np.cos` and `np.sin` should be swapped, what do you think? or do I have some misunderstanding?
![image](https://user-images.githubusercontent.com/23610315/207252763-97a96540-5994-4922-9d11-bb59bf7147d3.png)

**Comment by JanJan1995** [comment]
Cool! Thanks for your figure about BEV alignment @gengshi. Maybe I know the reason why the author using _cos_ () to calculate shift_y and using _sin_ () to calculate shift_x.  Cause you mess up the ego-x and ego-y. Actually, In BEV Image, the direction of car front is ego-y not ego-x. This is a figure about Lidar Device in _Nuscenes_ Dataset which will show you more details about direction:
![image](https://www.nuscenes.org/static/media/data.9ef46c59.png)

Thus, after swapping the name of ego-x and ego-y, the code works well!

**Comment by ciwei123** [comment]
@gengshi @JanJan1995 
Excuse me，Could you tell me **the BEV feature** in which coordinate space ? lidar_top or camera_front?  
Another question, What does the following code do?
        ```
delta_x = np.array([each['can_bus'][0]
                           for each in kwargs['img_metas']]) #each['can_bus'].shape=(18,), len(kwargs['img_metas'])=batch_size
        delta_y = np.array([each['can_bus'][1]
                           for each in kwargs['img_metas']])
        ego_angle = np.array(
            [each['can_bus'][-2] / np.pi * 180 for each in kwargs['img_metas']])
        grid_length_y = grid_length[0]
        grid_length_x = grid_length[1]
        translation_length = np.sqrt(delta_x ** 2 + delta_y ** 2)
        translation_angle = np.arctan2(delta_y, delta_x) / np.pi * 180
        bev_angle = ego_angle - translation_angle
        shift_y = translation_length * \
            np.cos(bev_angle / 180 * np.pi) / grid_length_y / bev_h
        shift_x = translation_length * \
            np.sin(bev_angle / 180 * np.pi) / grid_length_x / bev_w
        shift_y = shift_y * self.use_shift
        shift_x = shift_x * self.use_shift
        shift = bev_queries.new_tensor(
            [shift_x, shift_y]).permute(1, 0)  # xy, bs -> bs, xy

        if prev_bev is not None:
            if prev_bev.shape[1] == bev_h * bev_w:
                prev_bev = prev_bev.permute(1, 0, 2)
            if self.rotate_prev_bev:
                for i in range(bs):
                    # num_prev_bev = prev_bev.size(1)
                    rotation_angle = kwargs['img_metas'][i]['can_bus'][-1]
                    tmp_prev_bev = prev_bev[:, i].reshape(
                        bev_h, bev_w, -1).permute(2, 0, 1)
                    tmp_prev_bev = rotate(tmp_prev_bev, rotation_angle,
                                          center=self.rotate_center)
                    tmp_prev_bev = tmp_prev_bev.permute(1, 2, 0).reshape(
                        bev_h * bev_w, 1, -1)
                    prev_bev[:, i] = tmp_prev_bev[:, 0]

        # add can bus signals
        can_bus = bev_queries.new_tensor(
            [each['can_bus'] for each in kwargs['img_metas']])  # [:, :]
        can_bus = self.can_bus_mlp(can_bus)[None, :, :]
        bev_queries = bev_queries + can_bus * self.use_can_bus

```
`def point_sampling(self, reference_points, pc_range,  img_metas):`
Looking forward to your reply, thank you very much!!

**Comment by YTEP-ZHI** [comment]
@ciwei123 Lidar coordinate space, so the original codes are right. x corresponds to sin, and y to cos.
![image](https://user-images.githubusercontent.com/48089846/211323733-f5e26843-d85a-419a-8fa8-00a7aca3ffd7.png)

**Comment by whystopped** [comment]
![图片 1](https://github.com/fundamentalvision/BEVFormer/assets/51702507/3b022ca6-25a2-4eae-97cc-bfa4175e21c5)
@zhiqi-li I have a question about the rotation of `prev_bev`
https://github.com/fundamentalvision/BEVFormer/blob/master/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L143-L156
the calculated `rotation_angle` is the blue angle, when rotating `prev_bev`, I think the green angle, i.e. the `-rotation_angle` should be used rather than the original `rotation_angle`, is there anything wrong?

**Comment by usergxx** [comment]
> <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/51702507/292793391-345b20c8-b2c3-4c9b-ba0c-1691a15aba2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjIyMTksIm5iZiI6MTcyMjMyMTkxOSwicGF0aCI6Ii81MTcwMjUwNy8yOTI3OTMzOTEtMzQ1YjIwYzgtYjJjMy00YzliLWJhMGMtMTY5MWExNWFiYTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA2NDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzBkZDllNTExNjE4NzYzZmI2NjM0NTYzNjNlZGI1MzYwNzgzMjdmODhmYzc4ZWQ1NGZjZDNhZjBlMWI1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1APCsNQo17zfsNlg6flD-ELvlQvUAkoVnxhajLNrL3U">
> @zhiqi-li I have a question about the rotation of `prev_bev`
> 
> https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/bevformer/modules/transformer.py#L143-L156
> 
> the calculated `rotation_angle` is the blue angle, when rotating `prev_bev`, I think the green angle, i.e. the `-rotation_angle` should be used rather than the original `rotation_angle`, is there anything wrong?

hello， do you know why the angle is rotation_angle but not -rotation_angle ?  the shift is also
