### ISSUE TITLE
关于多任务联合

### ISSUE THREAD

**Issue by Bin-ze** [fundamentalvision/BEVFormer#142]
嗨，您好，非常感谢您的贡献，我仔细查看你的代码，表示非常敬佩！
我打算基于此复现muti-task任务，BEV作为其中间表示，就像您论文中提到的那样。
但是，作为复现的前期工作，我有一些简单的疑问想请教您：
1. 关于BEV分割label，是否类似于BEVerse或者VectormapNet，如果可能的话，可以将您实现的关于多任务的dataset类函数发到我的邮箱吗，万分感谢！
2. 我思考了下改动逻辑，发现基于您的代码修改多任务逻辑并不简单，主要包含几部分的改动：
* 数据处理，BBOX3d以及BEV seg，对齐，如果可以的话，这部分能否提供协助？
* decode部分，并行分别执行检测分割预测，计算loss并加权，如果可能的话，能告诉我检测分割的权重占比？
* 可视化部分，需要修改
* 计算指标部分，需要对结果进行format

除此之外，我仔细阅读代码，发现您在构建前后帧的时候并未处理前后帧不在一个scene里的情况，这里是为了增加复杂度吗？您在repo里解释了在测试的时候提到如果使用多卡将可能降低性能，是基于这样可能的原因，您能解答我这个问题吗？

如果可能的话，我希望可以跟您有进一步的交流，期待您的回复！

**Comment by chaojiyu** [comment]
您好，请问您基于BEVFormer实现多任务的想法实现了吗？还有BEVformer进行分割任务的代码是不是没有开源出来呢？期待您的回复！

**Comment by Bin-ze** [comment]
是的，我实现了分割，bevformer本身并没有开源分割的代码，因此如果是应用的话，需要自己设计分割head

发自我的iPhone
