### ISSUE TITLE
Error "ModuleNotFoundError: No module named 'tools'"

### ISSUE THREAD

**Issue by BrokenArrow1404** [fundamentalvision/BEVFormer#148]
I followed [Step-by-step installation instructions](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/install.md) and installed mmdet3d, timm and BEVFormer.
Then I tried to [Prepare nuScenes data](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/prepare_dataset.md) but got an error:

> (open-mmlab) hzx@HZXPC:~/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 10, in <module>
    from data_converter import indoor_converter as indoor
  File "/home/hzx/BEVFormer/tools/data_converter/indoor_converter.py", line 6, in <module>
    from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
ModuleNotFoundError: No module named 'tools'

and here is my file tree
![image](https://user-images.githubusercontent.com/43647008/211210158-f9255316-78a6-4ac6-a36a-66d4b5602f65.png)

**Comment by NightNightNight** [comment]
try set current path as python path use:export PYTHONPATH=./

**Comment by BrokenArrow1404** [comment]
> Try to set the current path to python path first with the following command. export PYTHONPATH=./

that works for me, thanks
