### ISSUE TITLE
BEV特征的方向是什么样的？

### ISSUE THREAD

**Issue by Bin-ze** [fundamentalvision/BEVFormer#153]
我想要知道得到的BEV特征的方向是怎样的？
得到的BEV特征是一个正方形，如果在图片坐标系下，H表示x轴，W表示y轴，那车辆行驶的方向是什么？还有BEV特征是在lidar坐标系下吗，怎样将它转换到图像坐标系？

**Comment by chenchen235** [comment]
请问您解决该问题了吗，我也有相同的疑问，万分感谢！
