### ISSUE TITLE
按照文档步骤，不过一直显示networkx 2.2 is installed but networkx>=2.8 is required by {'scikit-image'}  

### ISSUE THREAD

**Issue by atlantins** [fundamentalvision/BEVFormer#176]
![Snipaste_2023-05-22_17-33-31](https://github.com/fundamentalvision/BEVFormer/assets/55533086/4683f634-ac81-44b3-9d4c-77617e736fba)
Python setup.py install出现问题

**Comment by YoungQuasimodo** [comment]
把scikit-image的版本降低，执行：
pip install scikit-image==0.19.2
即可

**Comment by atlantins** [comment]
好的，感谢！

**Comment by ncepu5** [comment]
早点问呀，我也是这个问题

**Comment by SanMu116** [comment]
您好，我也在配置bevformer的环境，我是按照文档步骤。但是说我的numpy版本不匹配，我降低numpy版本以后也不行。请问您有遇到过类似的问题吗
![image](https://github.com/fundamentalvision/BEVFormer/assets/103253021/962df07f-9f97-42ab-8d7b-a6be3128cb37)

**Comment by atlantins** [comment]
> 
按理来说安装torch和torchvision的时候肯定会安装numpy，安装后面的库如果出现冲突，我也没有一个较好的方法，一般都是手动安装

**Comment by SanMu116** [comment]
嗯嗯，感谢！已经手动调整了版本

**Comment by xuefeng1130** [comment]
> 嗯嗯，感谢！已经手动调整了版本
<img width="1130" alt="image" src="https://github.com/fundamentalvision/BEVFormer/assets/113966288/287a28fa-82b8-4c2a-b07a-41eb82a7a56c">
同问，怎么解决呀

**Comment by Tongjiaxun** [comment]
> > 嗯嗯，感谢！已经手动调整了版本
> 
> <img alt="image" width="1130" src="https://user-images.githubusercontent.com/113966288/270876551-287a28fa-82b8-4c2a-b07a-41eb82a7a56c.png"> 同问，怎么解决呀

请问解决了吗

**Comment by xuefeng1130** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，我的邮箱已接收到您发来的邮件。待我处理后给您回复。

**Comment by zhishuifeiqian** [comment]
> > 嗯嗯，感谢！已经手动调整了版本
> 
> <img alt="image" width="1130" src="https://user-images.githubusercontent.com/113966288/270876551-287a28fa-82b8-4c2a-b07a-41eb82a7a56c.png"> 同问，怎么解决呀

遇到了一样的问题，请问解决了吗

**Comment by ncepu5** [comment]
解决了，pytouch版本不匹配
| |
中科院自动化所 武更
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月15日 14:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [fundamentalvision/BEVFormer] 按照文档步骤，不过一直显示networkx 2.2 is installed but networkx>=2.8 is required by {'scikit-image'} (Issue #176) |

嗯嗯，感谢！已经手动调整了版本

同问，怎么解决呀

遇到了一样的问题，请问解决了吗

**Comment by thiesymon** [comment]
this article could help us :             https://zhuanlan.zhihu.com/p/643741075

**Comment by xuefeng1130** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，我的邮箱已接收到您发来的邮件。待我处理后给您回复。
