### ISSUE TITLE
Modified, working installation steps for training on Ubuntu 16.04

### ISSUE THREAD

**Issue by mimichu** [fundamentalvision/BEVFormer#184]
I encountered a lot of issues when trying to get BEVFormer up and training following the provided installation instructions. 

So just want to share my modified installation steps I used for my local environment on a 16.04 Ubuntu machine that lead to a working BEVFormer environment as *a* reference here, hopefully could be of help to the community.

### **Local Machine Specs**
Outputs of `lsb_release -a`
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.7 LTS
> Release:	16.04
> Codename:	xenial

Relevant outputs of `nvcc --version`
> Cuda compilation tools, release 11.1, V11.1.105

### **Modified Installation Steps**
```
# original
conda create -n open-mmlab python=3.8 -y  
conda activate open-mmlab  
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html  

# added
pip install scipy  

# original
conda install -c omgarcia gcc-6   
pip install mmcv-full==1.4.0 
pip install mmdet==2.14.0  
pip install mmsegmentation==0.14.1  
git clone https://github.com/open-mmlab/mmdetection3d.git  
cd mmdetection3d  
git checkout v0.17.1   
pip install timm  

# added
pip install scikit-image==0.19.3 
pip install networkx==2.2 
pip install numpy==1.19.5  
pip install urllib3==1.26.16  
pip install numpy==1.21.0  
pip install pytz  
pip install ipython  
pip install setuptools==59.5.0  

# original
python setup.py install 
git clone https://github.com/fundamentalvision/BEVFormer.git  
cd BEVFormer  
mkdir ckpts  
cd ckpts && wget https://github.com/zhiqi-li/storage/releases/download/v1.0/r101_dcn_fcos3d_pretrain.pth  
```

**Comment by SizheWei** [comment]
thanks for this summary! 

when install mmdet3d, I have to do one more step before clone BEVFormer:

```
pip install pandas==1.4.4
python setup.py install
```

for references!
