### ISSUE TITLE
跑通测试效果的最低电脑配置？

### ISSUE THREAD

**Issue by LadissonLai** [fundamentalvision/BEVFormer#185]
@zhiqi-li 您好，非常感谢你们的出色工作。我了解到你们训练使用了8个80G的V100GPU，如果只想使用训练结果，跑通测试代码，电脑最低配置是多少呀？我目前的电脑配置是i7 10代，32G 内存，3070 8G显卡，能满足跑通测试结果的要求吗？
期待您的回复。

**Comment by htian01** [comment]
只跑 Inference是够的.
