### ISSUE TITLE
OSError: ./ckpts/fcos_r50_coco_2mmdet.pth is not a checkpoint file

### ISSUE THREAD

**Issue by rockywind** [fundamentalvision/BEVFormer#190]
Hi,
How to download the `fcos_r50_coco_2mmdet.pth`?

**Comment by htian01** [comment]
Here: 
![微信截图_20230803134058](https://github.com/fundamentalvision/BEVFormer/assets/14885636/37c6984f-24b7-4fb4-85eb-6af2c5590bcf)

https://pan.baidu.com/s/1Jh5Aq2YwcD6tdj7Sl5BB3g?pwd=5rij
