### ISSUE TITLE
bevformerv2 in CropResizeFlipImage seems to have a bug

### ISSUE THREAD

**Issue by GG-Bonds** [fundamentalvision/BEVFormer#196]
Lack of flipping the box

[                        box = self._box_transform(ann['bbox'], resize, crop, flip, img.size[0])[0]](https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/datasets/pipelines/augmentation.py#L131C28-L131C29)

**Comment by htian01** [comment]
Thanks for your note. Its achieved by flip the feature: 
https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/bevformer/detectors/bevformerV2.py#L104

You could also implement here, its no difference.
