### ISSUE TITLE
nuscenes全数据集怎么处理？

### ISSUE THREAD

**Issue by xuefeng1130** [fundamentalvision/BEVFormer#199]
<img width="307" alt="image" src="https://github.com/fundamentalvision/BEVFormer/assets/113966288/6899b664-a580-4cf3-8fcd-e937b8b5fa27">
按照readme中的目录结构
<img width="508" alt="image" src="https://github.com/fundamentalvision/BEVFormer/assets/113966288/feaf7a8b-76a1-4f89-b45b-978583250aa6">
需要逐个解压然后合并吗？合并过程中会出错
bash: /bin/mv: Argument list too long

**Comment by htian01** [comment]
Its the same for nuscense dataset in mmdetection3d. Check here for more information
https://mmdetection3d.readthedocs.io/en/v0.18.0/data_preparation.html#nuscenes

Your problem seems to be the bash code bug.
