### ISSUE TITLE
关于nuscenes_converter.py里平移操作的疑问

### ISSUE THREAD

**Issue by NeoKH** [fundamentalvision/BEVFormer#201]
https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/tools/data_converter/nuscenes_converter.py#L373

L372-L377这一部分代码的作用是将camera的外参转换到lidar坐标系。
但有一个地方不理解：
为什么在转换平移向量T时，对于ego2global（at camera timestamp）是先旋转后平移，而对于global2ego（at lidar timestamp）和ego2lidar是先平移后旋转？难道不应该统一先平移后旋转吗？先旋转后平移会有偏差吧？

我在不改变代码含义的情况下对代码进行了整理简化，如下图所示：
![image](https://github.com/fundamentalvision/BEVFormer/assets/39455503/ee82e1b3-cab8-4ac5-b174-e9612574c592)

**Comment by htian01** [comment]
推荐可视化看看. 顺序不对应该会直接投影框飞掉. 这个地方很微妙, 得仔细check下. 目前我可视化看没有什么问题.
