### ISSUE TITLE
who has a complete file structure？？

### ISSUE THREAD

**Issue by 1146065545** [fundamentalvision/BEVFormer#207]

**Comment by Chan-dh** [comment]
Hi, What is the complete structure

**Comment by 1146065545** [comment]
File sorting order




---Original---
From: ***@***.***&gt;
Date: Wed, Jan 17, 2024 21:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fundamentalvision/BEVFormer] who has a complete file structure？？ (Issue #207)




 
Hi, What is the complete structure

**Comment by Chan-dh** [comment]
> File sorting order
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Jan 17, 2024 21:55 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [fundamentalvision/BEVFormer] who has a complete file structure？？ (Issue #207) Hi, What is the complete structure — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

hi, this is my E-mail: chanhd@foxmail.com. thanks!
