### ISSUE TITLE
dataset training

### ISSUE THREAD

**Issue by hbsycym** [fundamentalvision/BEVFormer#209]
Since the dataset is too large, if I want to use part of the dataset for training, where should I set it up?

**Comment by htian01** [comment]
For most simple case, hard code on mmdet3d.
https://github.com/open-mmlab/mmdetection3d/blob/f1107977dfd26155fc1f83779ee6535d2468f449/mmdet3d/datasets/custom_3d.py#L64C12-L64C12
for example, sub sample to 1/5. 
From 
self.data_infos = self.load_annotations(self.ann_file)
to 
self.data_infos = self.load_annotations(self.ann_file)[::5] 

For more reasonable way, check here:
https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/datasets/nuscenes_dataset_v2.py#L18
add line:
self.data_infos  = self.data_infos[::5] 
# maybe modify more variable 

Or, construct a new dataset called nuscenes-subset

**Comment by wuhen777** [comment]
> For most simple case, hard code on mmdet3d. https://github.com/open-mmlab/mmdetection3d/blob/f1107977dfd26155fc1f83779ee6535d2468f449/mmdet3d/datasets/custom_3d.py#L64C12-L64C12 for example, sub sample to 1/5. From self.data_infos = self.load_annotations(self.ann_file) to self.data_infos = self.load_annotations(self.ann_file)[::5]
> 
> For more reasonable way, check here:
> 
> https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/datasets/nuscenes_dataset_v2.py#L18
> 
> 
> add line:
> self.data_infos = self.data_infos[::5]
> # maybe modify more variable
> Or, construct a new dataset called nuscenes-subset

Thank you for your suggestion. Now, when slicing the mini dataset, I will change the 64th line of BEVFormer/mmdeletion3d/mmdet3d/datasets/custom_1d. py from # self. data_infos=self. loaduannotations (self. annunfile) to
After self. data_infos=self. loadannotations (self. annunfile) [:: 5], the training time remains the same as before it was modified.
Meanwhile, if I am in line 26 of BEVFormer/projects/mmdet3d_plugin/datasets/nuscenes_dataset. py, that is, super()__ After init__ (* args, * * kwargs), add self. data_infos=self. data_infos [:: 5], and it is found that the training time has not changed. May I ask what is the reason for this
![before change](https://github.com/fundamentalvision/BEVFormer/assets/84837506/08bf3c2f-8c25-4c32-8004-65a6976a6d7e)
![after change](https://github.com/fundamentalvision/BEVFormer/assets/84837506/6d11b825-8911-488f-ba3e-f302d76d5739)
![2024-05-09 175548](https://github.com/fundamentalvision/BEVFormer/assets/84837506/c7316546-8af0-47e6-aafa-46cc67032675)
![2024-05-09 175609](https://github.com/fundamentalvision/BEVFormer/assets/84837506/89976350-57f0-4cdf-b0b5-75c37c683e36)
Looking forward to your answer
