### ISSUE TITLE
How to download "fcos_r50_coco_2mmdet.pth"?

### ISSUE THREAD

**Issue by skmadan** [fundamentalvision/BEVFormer#212]
How do I download "fcos_r50_coco_2mmdet.pth"?

It seems to be required by bevformerv2: https://github.com/fundamentalvision/BEVFormer/blob/master/projects/configs/bevformerv2/bevformerv2-r50-t8-24ep.py#L155

**Comment by htian01** [comment]
https://pan.baidu.com/s/1ynzlAt1DQbH8NkqmisatTw?pwd=fdcv#list/path=%2FBEVFormerV2
