### ISSUE TITLE
What's the purpose of changing img_norm_cfg for bevformer_tiny

### ISSUE THREAD

**Issue by Jian-danai** [fundamentalvision/BEVFormer#213]
In bevformer base and small
`img_norm_cfg = dict(mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)`

However, in tiny
`img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)`

**Comment by Doctor-James** [comment]
This is related to the pre-training model used, the tiny version uses torchvision's r50 pretrain model, while the small and base versions use the fcos3d pretrain model, and the two pre-training models use different img_norm_cfg when pre-training.

**Comment by Jian-danai** [comment]
@Doctor-James Thanks, that makes sense.

**Comment by GG-Bonds** [comment]
> 这个和使用的预训练模型有关，tiny版本使用的是torchvision的r50预训练模型，而small和base版本使用的是fcos3d预训练模型，两个预训练模型在预训练的时候使用的img_norm_cfg是不同的。

两者在性能上会相差多少
