### ISSUE TITLE
Question about the training of BEVFormerV2

### ISSUE THREAD

**Issue by gray311** [fundamentalvision/BEVFormer#217]
Hello, I've been trying to reproduce BEVFormerV2 recently, but according to the code, it seems that BEVFormerV2 doesn't support Batch Size > 1 during training, is this the case or do I have a misunderstanding. Because I think every sample within a batch needs to compute pre_bev features when batchsize > 1, but it's not in the code, it only uses the infos of img_meta[0].

https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/bevformer/detectors/bevformerV2.py#L195C9-L195C19

**Comment by htian01** [comment]
Yes, currently, the code only support training of batch size =1
