### ISSUE TITLE
Help with issue to prepare dataset

### ISSUE THREAD

**Issue by diegola123** [fundamentalvision/BEVFormer#223]
Hello All, 

I will appreciate any help you can provide me. 

When I am trying to prepare the dataset, I am receiving the following error:

```
> root@diego-Amd-Am5:/nuscenes/BEVFormer# python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data
> Traceback (most recent call last):
>   File "tools/create_data.py", line 10, in <module>
>     from data_converter import indoor_converter as indoor
>   File "/nuscenes/BEVFormer/tools/data_converter/indoor_converter.py", line 6, in <module>
>     from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
> ModuleNotFoundError: No module named 'tools.data_converter'
> root@diego-Amd-Am5:/nuscenes/BEVFormer# 
```

I tried to run the following command to include a new input in the Environment Variables, but so far, no luck.

export PYTHONPATH=$PYTHONPATH:"./"

Thanks for any help

Best Regards
Diego

**Comment by wuhen777** [comment]
indoor_converter.py 修改

from .s3dis_data_utils import S3DISData, S3DISSegData
from .scannet_data_utils import ScanNetData, ScanNetSegData
from .sunrgbd_data_utils import SUNRGBDData
#from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
#from tools.data_converter.scannet_data_utils import ScanNetData, ScanNetSegData
#from tools.data_converter.sunrgbd_data_utils import SUNRGBDData

改完之后试一遍，如果不行就像下面去加路径
export PYTHONPATH="/root/autodl-tmp/BEVFormer:$PYTHONPATH"

**Comment by lix19937** [comment]
see https://github.com/fundamentalvision/BEVFormer/pull/241#issuecomment-2049094853

**Comment by diegola123** [comment]
> rom .s3dis_data_utils import S3DISData, S3DISSegData
> from .scannet_data_utils import ScanNetData, ScanNetSegData
> from .sunrgbd_data_utils import SUNRGBDData

Sorry, I forgot to say Thank you. It did work.
