### ISSUE TITLE
Do any friends have trained ckpts.pth files? Can you please share them with me for testing，Thank you very much！有朋友可以分享一下训练好的ckpts.pth文件吗~~

### ISSUE THREAD

**Issue by xiaoma-zds** [fundamentalvision/BEVFormer#234]
Do any friends have trained ckpts.pth files? Can you please share them with me for testing，Thank you very much！有朋友可以分享一下训练好的ckpts.pth文件吗~~

**Comment by htian01** [comment]
Check here https://github.com/fundamentalvision/BEVFormer?tab=readme-ov-file#model-zoo
