### ISSUE TITLE
Performance get worse as the training step increases?

### ISSUE THREAD

**Issue by ZYang2077** [fundamentalvision/BEVFormer#239]
epoch4:
mAP: 0.0943
mATE: 1.0340
mASE: 0.3312
mAOE: 0.8871
mAVE: 1.1964
mAAE: 0.3339
NDS: 0.1919
epoch8:
mAP: 0.0000
mATE: 1.0594
mASE: 0.9016
mAOE: 1.1099
mAVE: 1.1118
mAAE: 0.9111
NDS: 0.0187

**Comment by htian01** [comment]
For such low mAP, there might be some data wrong. Check the provied log.
