### ISSUE TITLE
OSError: ./path/to/ckpts.pth is not a checkpoint file load checkpoint from local path: ./path/to/ckpts.pth

### ISSUE THREAD

**Issue by grunday** [fundamentalvision/BEVFormer#242]
Am I the only one who doesn't have this file?

![스크린샷, 2024-04-01 14-02-39](https://github.com/fundamentalvision/BEVFormer/assets/74305113/2b813ad5-96c9-4d2e-8bb7-6802057d5be2)

There was an error because the arguments could not be received because there was no file in the path. Where does everyone get path/to/ckpts.pth?

![스크린샷, 2024-04-01 14-03-55](https://github.com/fundamentalvision/BEVFormer/assets/74305113/303c62b2-a2f6-4025-ae47-beebba459a1f)

**Comment by Akshay6077** [comment]
Did you get a solution for this I am facing a similar issue?
